services:
  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: superolyauser
      POSTGRES_PASSWORD: 2StDRkCeJJJTNtd
      POSTGRES_DB: data
    command: postgres -c timezone=Europe/Moscow
    volumes:
      - "db_data:/var/lib/postgresql/data"
    networks:
      - botnet

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: olpar@bot.com
      PGADMIN_DEFAULT_PASSWORD: olpar1000
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
    ports:
      - "8080:80"   # <-- порт на хосте : порт в контейнере
    depends_on:
      - postgres
    networks:
      - botnet

  bot_app:
    build: 
      context: ./  
      dockerfile: dockerfile
    container_name: olya_bot_app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+psycopg://superolyauser:2StDRkCeJJJTNtd@postgres:5432/data
    networks:
      - botnet
    volumes:
      - ./:/app
      
volumes:
  db_data:
  pgadmin_data:

networks:
  botnet:
    driver: bridge