version: '3.8'

services:

  postgres:
    image: postgres:15-alpine
    restart: "no"  # избавляемся от автоматической перезагрузки
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      # Superuser username/password
      POSTGRES_USER: egikww
      POSTGRES_PASSWORD: egikkotik2021
      POSTGRES_DB: data
    command: postgres -c timezone=Europe/Moscow
    volumes:
      - "01-simple-alchemy-postgres:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: "no"
    ports:
      - "127.0.0.1:5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: olpar@bot.com
      PGADMIN_DEFAULT_PASSWORD: olpar1000
    volumes:
      - "01-simple-alchemy-pgadmin:/var/lib/ pgadmin"
    depends_on:
      - postgres

  app:
    build:
      context: .
      dockerfile: dockerfile   # если у тебя Dockerfile называется иначе, поменяй
    container_name: olya_bot_app
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    environment:
      # дополнительные переменные можно здесь, они будут подтягиваться из .env
      DATABASE_URL: ${DATABASE_URL:-postgresql://superuser:superpassword@postgres:5432/data}
    volumes:
      - ./:/app:cached
    networks:
      - botnet
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    container_name: bot_nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - botnet

  certbot:
    image: certbot/certbot
    container_name: bot_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly --webroot
             --webroot-path=/var/www/certbot
             --email ${LETSENCRYPT_EMAIL}
             --agree-tos
             --no-eff-email
             -d ${WEBHOOK_DOMAIN} || true"

volumes:
  01-simple-alchemy-pgadmin:
  01-simple-alchemy-postgres:

networks:
  botnet:
    driver: bridge