"""new_gen

Revision ID: 700411875a87
Revises: 97e4bb0c0468
Create Date: 2025-09-24 21:47:34.621557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700411875a87'
down_revision: Union[str, Sequence[str], None] = '97e4bb0c0468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'link')
    op.create_unique_constraint('uq_user_vacancy', 'vacancy_sent', ['user_id', 'vacancy_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_vacancy', 'vacancy_sent', type_='unique')
    op.add_column('vacancies', sa.Column('link', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
