"""add_table_args_to_userprofession

Revision ID: 7c884f62dc0c
Revises: 7aaae8e354d5
Create Date: 2025-09-24 14:42:32.079238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c884f62dc0c'
down_revision: Union[str, Sequence[str], None] = '7aaae8e354d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_profession', 'user_professions', ['user_id', 'profession_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_profession', 'user_professions', type_='unique')
    # ### end Alembic commands ###
