"""add_pricing_plans_new_gen2

Revision ID: 815ce2dda827
Revises: 9be429eead03
Create Date: 2025-09-26 00:57:07.012406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '815ce2dda827'
down_revision: Union[str, Sequence[str], None] = '9be429eead03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_price_offer_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('first_price_offer_id', sa.String(), nullable=True))
    op.drop_column('users', 'first_price_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_price_data', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'first_price_offer_id')
    op.drop_column('users', 'first_price_offer_code')
    # ### end Alembic commands ###
