"""vacancy_and_forwarding_source

Revision ID: 7a08b879dffb
Revises: b33678668762
Create Date: 2025-10-06 00:04:40.411101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a08b879dffb'
down_revision: Union[str, Sequence[str], None] = 'b33678668762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_tasks_active'), table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    op.add_column('vacancies', sa.Column('vacancy_source', sa.Text(), nullable=True))
    op.add_column('vacancies', sa.Column('forwarding_source', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'forwarding_source')
    op.drop_column('vacancies', 'vacancy_source')
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scheduled_for', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('interval', postgresql.INTERVAL(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('cron', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('scheduled_tasks_pkey')),
    sa.UniqueConstraint('label', name=op.f('scheduled_tasks_label_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_scheduled_tasks_active'), 'scheduled_tasks', ['active'], unique=False)
    # ### end Alembic commands ###
