"""add_message_id

Revision ID: 94d34bb68d15
Revises: 196cfdb06ad9
Create Date: 2025-09-25 09:54:30.686942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d34bb68d15'
down_revision: Union[str, Sequence[str], None] = '196cfdb06ad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy_sent', sa.Column('message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancy_sent', 'message_id')
    # ### end Alembic commands ###
