"""1_october_night

Revision ID: fc818f1e1598
Revises: 3b09a3c645e1
Create Date: 2025-10-01 01:01:49.912713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc818f1e1598'
down_revision: Union[str, Sequence[str], None] = '3b09a3c645e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('from_user_id', sa.BigInteger(), nullable=True))
    op.add_column('vacancy_sent', sa.Column('vacancy_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancy_sent', 'vacancy_text')
    op.drop_column('users', 'from_user_id')
    # ### end Alembic commands ###
