"""Add keyprof and stopwords

Revision ID: 61a2989b5fab
Revises: 993905e37850
Create Date: 2025-09-23 20:11:34.652048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a2989b5fab'
down_revision: Union[str, Sequence[str], None] = '993905e37850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stop_words',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    op.add_column('keywords', sa.Column('profession_name', sa.Text(), nullable=False))
    op.create_foreign_key(None, 'keywords', 'professions', ['profession_name'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'keywords', type_='foreignkey')
    op.drop_column('keywords', 'profession_name')
    op.drop_table('stop_words')
    # ### end Alembic commands ###
