"""add_url_to_vacancy

Revision ID: 97e4bb0c0468
Revises: 7c884f62dc0c
Create Date: 2025-09-24 21:26:07.823432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97e4bb0c0468'
down_revision: Union[str, Sequence[str], None] = '7c884f62dc0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'link')
    # ### end Alembic commands ###
