"""new_gen3

Revision ID: 196cfdb06ad9
Revises: a9865c3daedc
Create Date: 2025-09-24 22:21:42.711622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '196cfdb06ad9'
down_revision: Union[str, Sequence[str], None] = 'a9865c3daedc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy_queue', sa.Column('profession_id', sa.UUID(), nullable=False))
    op.drop_column('vacancy_queue', 'profession_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy_queue', sa.Column('profession_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('vacancy_queue', 'profession_id')
    # ### end Alembic commands ###
