"""add_pricing_plans_v3

Revision ID: 1548e89431da
Revises: 003f27e2c3bb
Create Date: 2025-09-26 00:11:36.262355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1548e89431da'
down_revision: Union[str, Sequence[str], None] = '003f27e2c3bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing_plans', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricing_plans', 'id')
    # ### end Alembic commands ###
