"""add_three_days_and_cancelled_sub_to_user

Revision ID: 81cf2a2e7a10
Revises: 971a11bba1ac
Create Date: 2025-09-28 17:56:51.443765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81cf2a2e7a10'
down_revision: Union[str, Sequence[str], None] = '971a11bba1ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('three_days_free_active', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cancelled_subscription_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cancelled_subscription_date')
    op.drop_column('users', 'three_days_free_active')
    # ### end Alembic commands ###
