"""add_admin_chat_to_vacancy

Revision ID: 97b388caae25
Revises: 3831a7c473be
Create Date: 2025-10-06 16:25:44.968067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97b388caae25'
down_revision: Union[str, Sequence[str], None] = '3831a7c473be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('admin_chat_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'admin_chat_url')
    # ### end Alembic commands ###
