"""add_cascade

Revision ID: 001d2370223c
Revises: 30da4b5146bd
Create Date: 2025-10-06 11:01:35.656370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001d2370223c'
down_revision: Union[str, Sequence[str], None] = '30da4b5146bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('keywords_profession_id_fkey'), 'keywords', type_='foreignkey')
    op.create_foreign_key(None, 'keywords', 'professions', ['profession_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_professions_profession_id_fkey'), 'user_professions', type_='foreignkey')
    op.create_foreign_key(None, 'user_professions', 'professions', ['profession_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('vacancies_profession_id_fkey'), 'vacancies', type_='foreignkey')
    op.create_foreign_key(None, 'vacancies', 'professions', ['profession_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('vacancy_sent_vacancy_id_fkey'), 'vacancy_sent', type_='foreignkey')
    op.create_foreign_key(None, 'vacancy_sent', 'vacancies', ['vacancy_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancy_sent', type_='foreignkey')
    op.create_foreign_key(op.f('vacancy_sent_vacancy_id_fkey'), 'vacancy_sent', 'vacancies', ['vacancy_id'], ['id'])
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.create_foreign_key(op.f('vacancies_profession_id_fkey'), 'vacancies', 'professions', ['profession_id'], ['id'])
    op.drop_constraint(None, 'user_professions', type_='foreignkey')
    op.create_foreign_key(op.f('user_professions_profession_id_fkey'), 'user_professions', 'professions', ['profession_id'], ['id'])
    op.drop_constraint(None, 'keywords', type_='foreignkey')
    op.create_foreign_key(op.f('keywords_profession_id_fkey'), 'keywords', 'professions', ['profession_id'], ['id'])
    # ### end Alembic commands ###
