"""add_is_autopay_to_user

Revision ID: d0c10a4091d1
Revises: 81cf2a2e7a10
Create Date: 2025-09-30 18:16:51.646614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c10a4091d1'
down_revision: Union[str, Sequence[str], None] = '81cf2a2e7a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_autopay', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_autopay')
    # ### end Alembic commands ###
