"""vachash

Revision ID: b33678668762
Revises: c2713fb9dfa2
Create Date: 2025-10-01 08:04:49.025700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33678668762'
down_revision: Union[str, Sequence[str], None] = 'c2713fb9dfa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('hash', sa.Text(), nullable=True))
    op.create_index(op.f('ix_vacancies_hash'), 'vacancies', ['hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancies_hash'), table_name='vacancies')
    op.drop_column('vacancies', 'hash')
    # ### end Alembic commands ###
