"""add_is_pay_status

Revision ID: 971a11bba1ac
Revises: 815ce2dda827
Create Date: 2025-09-26 02:52:18.580557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '971a11bba1ac'
down_revision: Union[str, Sequence[str], None] = '815ce2dda827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_pay_status', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_pay_status')
    # ### end Alembic commands ###
