name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /bot
            if [ ! -d "parbot/olya_parser_bot/.git" ]; then
                rm -rf parbot/olya_parser_bot
                git clone git@github.com:WilyHedgehog/olya_parser_bot.git parbot/olya_parser_bot
            fi
            cd parbot/olya_parser_bot
            git fetch --all
            git reset --hard origin/main
            docker compose down
            docker compose up -d --build
            docker image prune -f