name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /bot
            # Если репозитория нет — клонируем
            if [ ! -d "parbot/.git" ]; then
                git clone https://github.com/WilyHedgehog/olya_parser_bot.git parbot
            fi
            cd parbot
            # Обновляем код до последнего коммита main
            git fetch --all
            git reset --hard origin/main
            # Перезапуск docker-compose
            docker compose down
            docker compose up -d --build
            docker image prune -f