name: 🚀 Deploy to VPS

on:
  push:
    branches:
      - main   # запускаем только при пуше в main (или master)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем код (чтобы workflow видел файлы репо)
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Деплой на сервер через SSH
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /bot/parbot
            git fetch --all
            git reset --hard origin/main
            docker compose down
            docker compose up -d --build
            docker image prune -f